version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: forumdb
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'forumdb']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - forum

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: unless-stopped
    env_file: .env
    environment:
      HOST: 0.0.0.0
      PGHOST: postgres
      PGDATABASE: forumdb
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - forum
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  forum:
